apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::576290270995:user/AdminUser
      username: admin
      groups:
        - system:masters
